
import React from 'react';
import { AppState } from '../types'; 

interface FooterProps {
  onNavigate: (state: AppState) => void;
  hasResult: boolean;
  onOpenContactModal: () => void;
  onOpenInfoModal: (title: string, content: string) => void;
}

const Footer: React.FC<FooterProps> = ({ onNavigate, hasResult, onOpenContactModal, onOpenInfoModal }) => {
  const privacyPolicyContent = "This is a placeholder for our Privacy Policy. We are committed to protecting your privacy. Any personal information collected through this platform is used solely for the purpose of resume analysis and skill gap identification. We do not share your data with third parties without your explicit consent. Your resume content is processed securely and is never stored permanently after your session concludes, unless explicitly opted into a saving feature. For more details, please contact us.";
  const termsOfServiceContent = "Welcome to CareerCraft! By using our services, you agree to these Terms of Service. Our platform provides AI-powered resume optimization and career guidance. You agree not to misuse the service, interfere with its operation, or attempt to access it by any means other than through the interfaces provided by CareerCraft. All content generated by our AI is for informational purposes only and should not be considered professional legal or career advice. We reserve the right to modify or terminate services at any time.";
  const disclaimerContent = "The information provided by CareerCraft is for general informational and educational purposes only. All information on the site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, or completeness of any information or analysis provided. Your career success depends on many factors, and CareerCraft cannot guarantee specific results. Always consult with a qualified professional for personalized career advice.";
  const aboutMissionContent = "At CareerCraft, our mission is to empower individuals in their job search and career development journey. We believe in leveraging cutting-edge AI technology to provide accessible, intelligent tools for resume optimization, skill gap analysis, and personalized career roadmapping. Our goal is to demystify the hiring process and help every job seeker present their best self, increasing their chances of landing their dream job. We are dedicated to continuous improvement and user success.";


  return (
    <footer className="bg-slate-950 text-slate-300 py-16 px-6 lg:px-12">
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 lg:gap-8">
        {/* Brand Section */}
        <div className="space-y-6">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-indigo-600 rounded-xl flex items-center justify-center text-white text-sm shadow-lg">
              <i className="fa-solid fa-bolt-lightning"></i>
            </div>
            <span className="text-xl font-black text-white tracking-tighter italic uppercase">Career<span className="text-indigo-600">Craft</span></span>
          </div>
          <p className="text-sm text-slate-400 leading-relaxed max-w-xs">
            Empowering career progression with AI-driven resume optimization. Bridging skill gaps and achieving professional excellence through intelligent analysis.
          </p>
        </div>

        {/* Navigation Section */}
        <div className="space-y-5">
          <h4 className="text-[11px] font-black text-indigo-400 uppercase tracking-[0.2em] mb-4">Navigation</h4>
          <ul className="space-y-3">
            <li><button onClick={() => onNavigate(AppState.IDLE)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">Home</button></li>
            <li><button onClick={() => onNavigate(AppState.UPLOADING)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">Start Analysis</button></li>
            <li>
                <button 
                    onClick={() => onNavigate(AppState.RESULT)} 
                    disabled={!hasResult}
                    className={`text-sm font-medium ${!hasResult ? 'text-slate-500 cursor-not-allowed' : 'text-slate-300 hover:text-indigo-500 transition-colors'}`}
                >
                    My Report
                </button>
            </li>
            <li>
                <button 
                    onClick={() => onNavigate(AppState.ROADMAP)} 
                    disabled={!hasResult}
                    className={`text-sm font-medium ${!hasResult ? 'text-slate-500 cursor-not-allowed' : 'text-slate-300 hover:text-indigo-500 transition-colors'}`}
                >
                    Action Plan
                </button>
            </li>
          </ul>
        </div>

        {/* Legal Section */}
        <div className="space-y-5">
          <h4 className="text-[11px] font-black text-indigo-400 uppercase tracking-[0.2em] mb-4">Legal Map</h4>
          <ul className="space-y-3">
            <li><button onClick={() => onOpenInfoModal('Privacy Policy', privacyPolicyContent)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">Privacy Policy</button></li>
            <li><button onClick={() => onOpenInfoModal('Terms of Service', termsOfServiceContent)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">Terms of Service</button></li>
            <li><button onClick={() => onOpenInfoModal('Disclaimer', disclaimerContent)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">Disclaimer</button></li>
          </ul>
        </div>

        {/* About Us Section */}
        <div className="space-y-5">
          <h4 className="text-[11px] font-black text-indigo-400 uppercase tracking-[0.2em] mb-4">About Us</h4>
          <ul className="space-y-3">
            <li><button onClick={() => onOpenInfoModal('About Our Mission', aboutMissionContent)} className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium">About Our Mission</button></li>
            <li>
                <button 
                    onClick={onOpenContactModal} 
                    className="text-slate-300 hover:text-indigo-500 transition-colors text-sm font-medium"
                >
                    Contact Us
                </button>
            </li>
          </ul>
        </div>
      </div>

      <div className="border-t border-slate-800 mt-16 pt-8 text-center text-slate-500 text-xs uppercase tracking-wider">
        © 2024 CareerCraft. All Rights Reserved.
      </div>
    </footer>
  );
};

export default Footer;